config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'shortlinks#index'
  resources :shortlinks
  get '/:short_url', to: 'shortlinks#redir' # keep last so shorturl never overrides
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortlink.rb
class Shortlink < ApplicationRecord
  before_validation :smart_add_url_protocol

  validates :short_url, presence: true,
                    length: { minimum: 1 },
                    uniqueness: true
  validates :long_url, presence: true, :url => true

  protected

  # CREDIT TO https://stackoverflow.com/a/7908693/3247102
  def smart_add_url_protocol
    unless self.long_url[/\Ahttp:\/\//] || self.long_url[/\Ahttps:\/\//]
      self.long_url = "http://#{self.long_url}"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/shortlinks_controller.rb
class ShortlinksController < ApplicationController

  def index
    @shortlinks = Shortlink.order("clicks DESC").all
  end

  def show
    @shortlink = Shortlink.find(params[:id])
  end

  def new
    @shortlink = Shortlink.new
  end

  def edit
    @shortlink = Shortlink.new

    if current_user.blank?
      # EROR: nobody logged in
      redirect_to shortlinks_path, :alert => "Please log in to edit this link."
    elsif (current_user.email != ENV["ADMIN_EMAIL"])
      # SUCCESS: user is admin, let them do whatever they want
      @shortlink = Shortlink.find(params[:id])
    elsif @shortlink.user_id.blank?
      # ERROR: shortlink was created by a guest user
      redirect_to shortlinks_path, :alert => "You can not edit this link because it was created by a guest user. It can only be edited by an admin."
    elsif (current_user.id == @shortlink.user_id)
      # SUCCESS: current_user created the link
      @shortlink = Shortlink.find(params[:id])
    elsif (current_user.id != @shortlink.user_id)
      # ERROR: current_user did not create the link
      redirect_to shortlinks_path, :alert => "You can not edit this link. It was created by another user."
    else
      # ERROR: catch all
      redirect_to shortlinks_path, :alert => "An unknown error has occurred. Please contact shortlinks-api@gmail.com if this happens again."
    end
  end

  def create
    @shortlink = Shortlink.new(shortlink_params)

    if current_user.blank?
      @shortlink.user_id = nil
    else
      @shortlink.user_id = current_user.id
    end

    if @shortlink.save
      redirect_to @shortlink
    else
      # something went wrong when saving, reload new
      render 'new'
    end
  end

  def update
    @shortlink = Shortlink.find(params[:id])

    if @shortlink.update(shortlink_params)
      redirect_to @shortlink
    else
      # something went wrong when updating, reload edit
      render 'edit'
    end
  end

  def destroy
    @shortlink = Shortlink.find(params[:id])

    if current_user.blank?
      # EROR: nobody logged in
      redirect_to shortlinks_path, :alert => "Please log in to delete this link."
    elsif (current_user.email != ENV["ADMIN_EMAIL"])
      # SUCCESS: user is admin, let them do whatever they want
      @shortlink.destroy
      redirect_to shortlinks_path # go back to all shortlinks
    elsif @shortlink.user_id.blank?
      # ERROR: shortlink was created by a guest user
      redirect_to shortlinks_path, :alert => "You can not edit this link because it was created by a guest user. It can only be deleted by an admin."
    elsif (current_user.id == @shortlink.user_id)
      # SUCCESS: current_user created the link
      @shortlink.destroy
      redirect_to shortlinks_path # go back to all shortlinks
    elsif (current_user.id != @shortlink.user_id)
      # ERROR: current_user did not create the link
      redirect_to shortlinks_path, :alert => "You can not delete this link. It was created by another user."
    else
      # ERROR: catch all
      redirect_to shortlinks_path, :alert => "An unknown error has occurred. Please contact shortlinks-api@gmail.com if this happens again."
    end
  end

  def redir
    @shortlink = Shortlink.find_by(short_url: params[:short_url])

    if @shortlink
      @shortlink.increment!(:clicks)
      redirect_to @shortlink.long_url
    else
      render :template =>"/shortlinks/404-link", :status => 404
    end
  end

  private
    def shortlink_params
      params.require(:shortlink).permit(:short_url, :long_url, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.email == ENV["ADMIN_EMAIL"]
      @users = User.all
    else
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortlinks_helper.rb
module ShortlinksHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p class="text-center copyright-text">radl.ink was built with ♥ by <a href='http://github.com/nsafai' class="copyright-text">Nicolai Safai</a></p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class="normal-li"><%= link_to 'My account', edit_user_registration_path %></li>
  <li class="normal-li"><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li class="normal-li"><%= link_to 'Log in', new_user_session_path %></li>
  <li class="normal-li"><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'radlink', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="normal-li">
  <%= link_to 'All links', shortlinks_path %>
</li>
<li class="">
  <%= link_to 'New link', new_shortlink_path, :class=>"cta" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Language" content="en_US" />
    <meta name="google" content="notranslate" />
    <title><%= content_for?(:title) ? yield(:title) : "radlinks" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A rad custom shortlink generator" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="content-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shortlinks/404-link.html.erb
<div class="container margin-top">
  <h1 class="text-center">Broken link</h1>
  <h2 class="text-center margin-bot">Hmm that URL does not exist</h2>
  <img src="https://media.giphy.com/media/NTY1kHmcLsCsg/giphy.gif" width="480" height="398" frameBorder="0" alt="sad face img" class="margin-bot" />
</div>

app/views/shortlinks/_form.html.erb
<%= form_with model: @shortlink, local: true do |form| %>

  <% if @shortlink.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shortlink.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @shortlink.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :short_URL %><br>
    radl.ink/<%= form.text_field :short_url, placeholder: "custom_url" %>
  </div>

  <div class="form-group">
    <%= form.label :original_URL %><br>
    <%= form.text_field :long_url, placeholder: "http://www.example.com/thing/23", :class=>"orig-url-field" %>
  </div>

  <p>
    <%= form.submit 'Save', :class => 'button center' %>
  </p>
<% end %>

app/views/shortlinks/edit.html.erb
<div class="container margin-top">
  <div class="authform">
    <h3>Edit Shortlink</h3>

    <%= render 'form' %>

    <%= link_to '← Back', shortlinks_path %>

  </div>
</div>

app/views/shortlinks/index.html.erb
<div class="container margin-top">

  <div class="table-title-and-button">
    <h1>All links</h1>
    <%= link_to 'New Link', new_shortlink_path, :class=>"btn btn-primary cta" %>
  </div>

  <table class="table table-responsive table-hover">
    <tr class="table-first-row">
      <th>Short URL</th>
      <th>Original URL</th>
      <th># Clicks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @shortlinks.each do |shortlink| %>
      <tr>
        <td><%= shortlink.short_url %></td>
        <td><a href="<%= shortlink.long_url %>"><%= shortlink.long_url %></a></td>
        <td><%= shortlink.clicks %></td>
        <td><%= link_to 'View', shortlink_path(shortlink) %></td>
        <td><%= link_to 'Edit', edit_shortlink_path(shortlink) %></td>
        <td><%= link_to 'Delete', shortlink_path(shortlink),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<div>

app/views/shortlinks/new.html.erb
<div class="container margin-top">
  <div class="authform">
    <h3>New Shortlink</h3>

    <%= render 'form' %>

    <%= link_to '← Back', shortlinks_path %>

  </div>
</div>

app/views/shortlinks/show.html.erb
<div class="container margin-top show-link-details">

  <h1>Link Details</h1>

  <p>
    <strong>Short URL:</strong>
    <%= @shortlink.short_url %>
  </p>

  <p>
    <strong>Original URL:</strong>
    <%= @shortlink.long_url %>
  </p>

  <p>
    <strong># Clicks:</strong>
    <%= @shortlink.clicks %>
  </p>

  <%= link_to '← Back', shortlinks_path %> |
  <%= link_to 'Edit', edit_shortlink_path(@shortlink) %>

</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>